# Change these first
owner: compada # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Marketing Pages
    url: https://www.compada.io
  # - name: App
  #   url: https://app.compada.dev
  # - name: API
  #   url: https://api.compada.dev/healthz

assignees: # Users to assign downtime issues (optional)
  - dudo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.compada.dev
  # baseUrl: /your-repo-name
  logoUrl: https://www.compada.io/images/favicon.svg
  faviconSvg: https://www.compada.io/images/favicon.svg
  favicon: https://www.compada.io/images/favicon.ico
  name: Compada Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
